appinfo/app.php

@cdamken that's why you always come back to me :P 
Activities have never been expired :see_no_evil: 
@karlitschek please approve 8.0.0 
@fossxplorer please review

Register the expire background job, so old activities are expired

---

lib/backgroundjob/emailnotification.php

Maybe helps spotting problems.
as discussed with @nickvergessen in IRC

log if a notification mail could not be set

---

lib/parameterhelper.php
tests/parameterhelpertest.php

Fix wrong/broken avatar and displayname for remote user actions in feed

---

js/script.js

[Stable7] Trim the response, before trying to add it to the output

---

rss.php

replace deprecated config calls with proper method calls

---

.travis.yml

See http://docs.travis-ci.com/user/build-configuration/#Using-regular-expressions
@DeepDiver1975

Correctly build the stable8 branch aswell

---

.travis.yml

Backport of #229 
and fixing ownCloud target branch in stable8

Travis stable8 testing

---

appinfo/app.php
appinfo/application.php
extension/files.php
extension/files_sharing.php
lib/data.php
lib/datahelper.php
lib/grouphelper.php
lib/hooks.php
lib/navigation.php
lib/parameterhelper.php
lib/usersettings.php
tests/apitest.php
tests/applicationtest.php
tests/datahelpertest.php
tests/datatest.php
tests/extensionfilestest.php
tests/grouphelpertest.php
tests/navigationtest.php
tests/parameterhelpertest.php
tests/usersettingstest.php

Create activity files extension

---

lib/data.php

Correctly use placeholders for notification types

---

tests/backgroundjob/emailnotificationtest.php
tests/backgroundjob/expireactivitiestest.php
tests/controller/activitiestest.php
tests/displaytest.php
tests/personaltest.php

Some basic tests to include all files into the test suite (apart from rss.php)
@LukasReschke

Add unit tests to cover all constructors and classes at least once

---

lib/backgroundjob/emailnotification.php

Backport of #244 
@LukasReschke

[Stable8] Use a valid timezone name when no timezone is set

---

lib/backgroundjob/emailnotification.php

@LukasReschke @DeepDiver1975 
Backporting the fix from #246 to stable8

[Stable8] Do not try to use empty values

---

controller/settings.php
js/script.js
js/settings.js
tests/controller/settingstest.php

Remove the status attribute and display a success message instead

---

lib/backgroundjob/emailnotification.php

@LukasReschke as per your https://github.com/owncloud/activity/pull/244#issuecomment-75732363

[Stable8] Use the servers timezone instead of UTC

---

appinfo/application.php
lib/backgroundjob/emailnotification.php
lib/mailqueuehandler.php
lib/mockutilsendmail.php
tests/backgroundjob/emailnotificationtest.php
tests/mailqueuehandlertest.php

Testcoverage for email stuff

---

lib/mailqueuehandler.php

Backport #251
Tests are in master only #246
@DeepDiver1975 @karlitschek approve backport?

Use displayname as user recipient in emails

---

appinfo/application.php
lib/consumer.php
tests/consumertest.php

Fix #250 
@LukasReschke maybe you want to have a look :dancer:

Fix incorrect magic for "self action" check

---

appinfo/application.php
lib/parameterhelper.php
tests/datahelpertest.php
tests/grouphelpertest.php
tests/parameterhelpertest.php

Only add avatar placeholder when avatars are enabled

---

ajax/fetch.php
lib/api.php
lib/mailqueuehandler.php
lib/parameterhelper.php
rss.php
tests/datahelpertest.php
tests/grouphelpertest.php
tests/parameterhelpertest.php

Related #257 (master), #258 (stable8), #256 (issue)

[Stable7] Fix disabled avatars on stable7

---

appinfo/application.php
lib/mailqueuehandler.php
lib/parameterhelper.php
tests/datahelpertest.php
tests/grouphelpertest.php
tests/navigationtest.php
tests/parameterhelpertest.php

Backport of #257 
Related #256

[Stable8] Disabled avatars

---

appinfo/application.php
lib/parameterhelper.php
tests/datahelpertest.php
tests/grouphelpertest.php
tests/parameterhelpertest.php

Grouping by username does not use display names

---

css/style.css

fix time tooltip not showing

---

js/script.js

Fix message for empty filter

---

lib/backgroundjob/emailnotification.php
lib/mailqueuehandler.php
templates/email.notification.php
tests/mailqueuehandlertest.php

Fix #267 
@karlitschek as discussed. The limit has been set to 200.

Limit the number of selected email entries per user

---

.travis.yml

Also to keep track of https://github.com/owncloud/core/pull/15496

Add some status information to travis output

---

js/script.js

Remove fade

---

controller/settings.php
tests/controller/settingstest.php

The defined route does not exists and throws an error 500
@nickvergessen

Fix link to RSS

---

.travis.yml

Regex testing: https://regex101.com/r/uT9zU4/2
Update script: https://github.com/nickv-oc/travis-branch-only-update-script

Update the branches.only setting in .travis.yml

---

js/script.js
templates/stream.app.navigation.php
tests/navigationtest.php

Issue 293 add active class li element

---

lib/fileshooks.php

Fix the detection of self-actions on files activities

---

lib/hooks.php

[stable8] Fix the detection of self-actions on files activities

---

controller/settings.php
lib/fileshooks.php
lib/parameterhelper.php
lib/usersettings.php
templates/email.notification.php
templates/stream.app.navigation.php

Caused by https://github.com/owncloud/core/pull/16065
@MorrisJobke @DeepDiver1975

Fix the discouraged equal / unequal operators

---

lib/display.php

Fix #310 
@jospoortvliet mind testing ;)
Otherwise @MorrisJobke

Correctly generate links around the preview with scrollto= parameter

---

appinfo/preupdate.php

Ref https://github.com/owncloud/core/issues/16812

[stable7] Add Oracle-specific workaround for changing a column type

---

lib/parameterhelper.php
tests/parameterhelpertest.php

Fix "and x more" parameter list

---

.scrutinizer.yml

Copying from https://github.com/owncloud/mail/commit/09188f228bfd2006845a39306e82edec660fad37
@LukasReschke

Add a higher timeout for code-coverage

---

appinfo/application.php
appinfo/update.php
controller/activities.php
controller/settings.php
js/settings.js
lib/api.php
lib/backgroundjob/emailnotification.php
lib/backgroundjob/expireactivities.php
lib/display.php
lib/fileshooks.php
lib/navigation.php
lib/parameterhelper.php
templates/personal.php
templates/stream.list.php
tests/controller/activitiestest.php

Removing most of the phpstorm complaints
data.php has not been touched, it will be part of another PR.
@MorrisJobke @LukasReschke

Deprecation cleanup after 8.1

---

tests/backgroundjob/expireactivitiestest.php
tests/displaytest.php
tests/navigationtest.php

The fell down from 100 with some recent patches.

Increase coverage back to 100

---

lib/display.php

Fix #329 
Using the same "hack" as the file list:
https://github.com/owncloud/core/blob/master/apps/files/lib/helper.php#L80
@jancborchardt 
we can then backport this until stable8 I think

Use the SVG icon like in the file list

---

appinfo/application.php
lib/parameterhelper.php
tests/datahelpertest.php
tests/grouphelpertest.php
tests/parameterhelpertest.php

Do not use deprecated Util::linkTo()

---

tests/usersettingstest.php

Replace hashtag comments with double slashes

---

controller/settings.php
js/settings.js
lib/data.php
templates/personal.php

Issue 302 settings improvements

---

tests/controller/settingstest.php

Bringing the test coverage back to 100%

Add unit tests for the new array logic

---

.gitignore
.travis.yml
js/script.js
tests/js/karma.config.js
tests/js/package.json
tests/js/scriptSpec.js

Fixes https://github.com/owncloud/activity/issues/360
@nickvergessen 
Note that this is only the ground work. Unit tests to be written separately (at least for newly introduced code!)
Let's see if this runs properly on travis.

Added JS unit test runner

---

css/style.css
js/activitytabview.js
tests/js/activitytabviewSpec.js

Fix #378 
Fix #377 
@jancborchardt

Fix sidebar issues

---

templates/rss.php
tests/template/rsstest.php

Required for multi line message bodies

Fix line breaks in RSS feed

---

tests/bootstrap.php

Caused by owncloud/core#18839 and the parents

Fix unit tests partly

---

lib/mailqueuehandler.php
templates/email.notification.php
tests/backgroundjob/emailnotificationtest.php
tests/mailqueuehandlertest.php

Avoid possible wrong translations of the also confusing time information

---

appinfo/application.php
lib/fileshooks.php
lib/fileshooksstatic.php
tests/fileshookstest.php

Add reshare activities

---

templates/personal.php

required for owncloud/core#18735

Modify checkboxes to work with new style

---

css/style.css

Similar to https://github.com/owncloud/core/pull/19121, but for the Activity. Please review @owncloud/designers @schiesbn @nickvergessen

fix Files sidebar Activity layout

---

lib/fileshooks.php
tests/fileshookstest.php

No reshare activities for owner when they share themselves

---

templates/personal.php
tests/controller/settingstest.php

Applying the new checkbox style based on owncloud/core#19329.

Apply new checkbox style in personal page

---

js/filesplugin.js

@nickvergessen 
Requires https://github.com/owncloud/core/pull/19404

Make activity tab the first of the default tabs

---

lib/grouphelper.php

Fix #395 
@MorrisJobke @PVince81 
---
Unit tests fail because of wrong core branch, CI branch at https://github.com/owncloud/activity/pull/403

Set the formatting object so Extensions can adjust

---

appinfo/application.php
controller/feed.php
tests/controller/feedtest.php
tests/datatest.php

@MorrisJobke 
Fixes broken master

Use l10n factory instead of non-existing method

---

templates/personal.php

Fixes partly owncloud/core#19724

Change the checkbox style

---

appinfo/info.xml

Update versions for 9.0

---

lib/fileshooks.php
lib/viewinfocache.php
tests/controller/activitiestest.php
tests/fileshookstest.php
tests/lib/viewinfocachetest.php

Catch not found exception

---

js/script.js

Thanks for teaching @PVince81 
Mind reviewing?

Fix the back and forward buttons on activitiy filters

---

js/script.js

@PVince81 lets backport this to 8.2.1
Backport of #425 
@karlitschek can you approve?

[8.2] Fix the back and forward buttons on activitiy filters

---

templates/stream.app.navigation.php

Please review @nickvergessen @Henni @owncloud/designers 
We should also backport this since the new checkboxes should be used for 8.2 everywhere. @karlitschek

use new checkbox style for in-app settings

---

lib/fileshooks.php
tests/fileshookstest.php

Improves behaviour when sharing with a lot of users in one group:
https://github.com/owncloud/core/issues/19639

Batch the searchUser for group shares

---

controller/activities.php
js/script.js
lib/api.php
lib/grouphelper.php
lib/parameter/collection.php
lib/parameter/factory.php
lib/parameter/iparameter.php
lib/parameter/parameter.php
tests/controller/activitiestest.php
tests/grouphelpertest.php
tests/parameter/collectiontest.php
tests/parameter/parametertest.php

Preparation for consolidation with the OCS endpoint for #405

Clean and fix the output of the controller endpoint

---

tests/apitest.php
tests/appinfo/applicationtest.php
tests/appinfo/updatetest.php
tests/backgroundjob/emailnotificationtest.php
tests/backgroundjob/expireactivitiestest.php
tests/consumertest.php
tests/controller/activitiestest.php
tests/datadeleteactivitestest.php
tests/datatest.php
tests/fileshookstest.php
tests/hooksdeleteusertest.php
tests/mailqueuehandlertest.php
tests/personaltest.php

Fixes failing master unit tests

Fix local testing

---

js/script.js

@enoch85 please test this
Fix #441

Fix lazy loading of activities after scrolling

---

.travis.yml
appinfo/application.php
controller/activities.php
controller/feed.php
js/script.js
lib/api.php
lib/datahelper.php
lib/formatter/baseformatter.php
lib/formatter/cloudidformatter.php
lib/formatter/fileformatter.php
lib/formatter/iformatter.php
lib/formatter/userformatter.php
lib/parameter/collection.php
lib/parameter/factory.php
lib/parameter/iparameter.php
lib/parameter/parameter.php
templates/rss.php
templates/stream.body.php
tests/controller/activitiestest.php
tests/datahelpertest.php
tests/formatter/baseformattertest.php
tests/formatter/cloudidformattertest.php
tests/formatter/fileformattertest.php
tests/formatter/userformattertest.php
tests/parameter/collectiontest.php
tests/parameter/factorytest.php
tests/parameter/parametertest.php
tests/template/rsstest.php

Fix #437 
Fix #440 
Should merge https://github.com/owncloud/announcementcenter/issues/39 right after

Better "and x more" handling

---

controller/feed.php
lib/api.php
lib/mailqueuehandler.php
lib/plaintextparser.php

Fix #450
1. Generate email activities
2. Trigger sending (modify lastest_sent in activity_mq, last_run in jobs)
3. Check email
`You shared welcome.txt with Test One`
`You shared <file link="http://localhost/ownCloud/master/core/index.php/apps/files/?dir=/&scrollto=welcome.txt" id="">welcome.txt</file> via link`

Deduplicate parsing and fix parsing in emails

---

controller/ocsendpoint.php
js/activitytabview.js
js/formatter.js
js/script.js
lib/fileshooksstatic.php
templates/stream.body.php
tests/controller/ocsendpointtest.php
tests/js/activitytabviewSpec.js
tests/js/karma.config.js

Fix parsing in the sidebar

---

lib/navigation.php

Now I can browse my activities again :)
CC: @nickvergessen

Fix OC_L10N usage

---

js/script.js

Fix the JS code to be compliant

---

lib/fileshooks.php
lib/formatter/fileformatter.php
tests/fileshookstest.php
tests/formatter/fileformattertest.php

Always store the file id with file parameters

---

lib/fileshooks.php
lib/fileshooksstatic.php
tests/fileshookstest.php

Fix #100 
Messages appear untranslated until https://github.com/owncloud/core/pull/22281
@rullzer review please

Add activities for unshare operations

---

appinfo/info.xml

Ref https://github.com/owncloud/core/issues/20962

Update the version to make sure background jobs are added again

---

css/style.css

fix message style in activity view

---

controller/ocsendpoint.php
tests/controller/ocsendpointtest.php

Fix #482 
Can you confirm @SchroSct

Fix the link for images of deleted files

---

controller/ocsendpoint.php
tests/controller/ocsendpointtest.php

[9.0] Fix the link for images of deleted files

---

lib/mailqueuehandler.php

[9.0] Do not register CSRF token

---

js/script.js

Fix infinite loop with request when headers are manipulated

---

js/script.js

[9.0] Fix infinite loop with request when headers are manipulated

---

lib/fileshooks.php

File not found? Sounds weird, but this happens before 9.1:
https://github.com/owncloud/core/issues/23212
Chunk assembling triggered the exact same hooks twice.
The first call however is before the file is in the database.
So when trying to get the owner, the file can not be found.
But since the second hook will come along, we simply ignore this.

Ignore \OCP\Files\NotFoundException on chunk assembling

---

lib/mailqueuehandler.php
tests/mailqueuehandlertest.php

Set the current user for emails

---

lib/mailqueuehandler.php
tests/mailqueuehandlertest.php

[9.0] Set the current user for email formatting

---

appinfo/database.xml
appinfo/info.xml

Add an index for the object based query from the sidebar plugin

---

controller/settings.php
lib/usersettings.php
tests/usersettingstest.php

Fix owncloud/core#23761
@alankeny can you test this?

Store the preferences as integers for postgres

---

controller/settings.php
lib/usersettings.php
tests/usersettingstest.php

[8.2] Store the preferences as integers for postgres

---

controller/ocsendpoint.php
tests/controller/ocsendpointtest.php

Fix #481 
Thanks @digsig for the error message. Can you test, whether this PR fixes your issue?
Just copy the patch for the `controller/ocsendpoint.php` file.

Handle "false" returned by getFileInfo()

---

controller/ocsendpoint.php
tests/controller/ocsendpointtest.php

[9.0] Handle "false" returned by getFileInfo()

---

appinfo/application.php
lib/fileshooks.php
lib/navigation.php
tests/fileshookstest.php

Fix #508 
@rabauke Can you test this?
It will only work for new entries thou :(

Absolute URLs are generated incorrectly

---

appinfo/application.php
lib/fileshooks.php
lib/navigation.php
tests/fileshookstest.php

Backport 509 rss links

---

appinfo/application.php
appinfo/info.xml
appinfo/update.php
controller/settings.php
lib/consumer.php
lib/data.php
lib/navigation.php
templates/personal.php
tests/backgroundjob/emailnotificationtest.php
tests/consumertest.php
tests/controller/settingstest.php
tests/datatest.php
tests/navigationtest.php

1. Make sure the checkbox is **not** checked
* Upload a file
* Comment on a file
* Check that you have an activity about the comment, but not about the upload
Ref #504 Step 1.

"list self action" should only affect file create, change, delete and restore

---

js/activitycollection.js
js/activitytabview.js
tests/js/activitycollectionSpec.js
tests/js/activitytabviewSpec.js

Add a button to load more activities in the sidebar

---

js/activitymodel.js
js/activitytabview.js
tests/js/activitytabviewSpec.js

Should backport the last commit to 9.0: https://github.com/owncloud/activity/commit/d4a59fd7f850e25dc8bbedc4936bc266d63c4a90

Fix displaying of the date in the sidebar

---

tests/apitest.php
tests/consumertest.php
tests/datatest.php
tests/navigationtest.php
tests/usersettingstest.php

Move the manager

---

js/activitytabview.js
tests/js/activitytabviewSpec.js

Backport of #516 
1. Enable activity app
2. Create a new file
3. Open sidebar of the file
4. On the create activity try to find the date

[9.0] Fix displaying of the date in the sidebar

---

appinfo/info.xml
lib/FilesHooks.php

Fixes https://github.com/owncloud/core/issues/24938
A bit convoluted but does the job.
Ideally at some point core should have an API to better distinguish a local user from a remote one.
@mmattel @DeepDiver1975  please review and test

Fix activity fed user

---

lib/fileshooks.php

Backport of https://github.com/owncloud/activity/pull/531 to stable9
@mmattel @ppaysant

[stable9] Fix activities when owner is a federated share user

---

lib/FilesHooks.php

Backport of https://github.com/owncloud/activity/pull/531 to stable9.1
@mmattel @ppaysant

[stable9.1] Fix activities when owner is a federated share user

---

js/activitytabview.js

Required for #504 Checkbox 3
Required for owncloud/core#24275

Allow OCA.Activity.Plugins to help rendering activities in the sidebar

---

README.md

Update README with recent branches status

---

lib/Data.php

- saves traffic
- saves possible CLOB to string conversion
found while reviewing https://github.com/owncloud/activity/pull/546

select only necessary colums

---

.travis.yml
js/activitytabview.js
tests/bootstrap.php

Backport of https://github.com/owncloud/activity/pull/530 to stable9.1
@DeepDiver1975

[stable9.1] fix 529: Avatar image in activity tab broken for "remote user"

---

js/activitytabview.js

This time only merge later for 9.1.4

fix 529: Avatar image in activity tab broken for "remote user"

---

lib/AppInfo/Application.php
lib/Formatter/GroupFormatter.php
lib/Parameter/Factory.php
tests/Formatter/GroupFormatterTest.php
tests/Parameter/FactoryTest.php
tests/js/package.json

Show displayName instead of group id
Signed-off-by: Sujith H <sharidasan@owncloud.com>

Show displayName instead of group id

---

CHANGELOG.md
appinfo/info.xml

fixes: https://github.com/owncloud/activity/issues/590
fixes: https://github.com/owncloud/activity/issues/591

Building app release v2.3.6-beta1

---

lib/GroupHelper.php
tests/GroupHelperTest.php

Fix grouping for share messages second try

---

CHANGELOG.md
appinfo/info.xml

For https://github.com/owncloud/activity/issues/621

Update version and changelog for 2.3.7

---

CHANGELOG.md

release 2.3.7

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/activity/issues/662

Release 2.4.1

---

.drone.yml
Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/ActivityPage.php
tests/acceptance/features/webUIActivity/list.feature

Setup the Acceptance tests framework. And add example webUI test.
#627 & #613
:robot:

Setup webUI acceptance tests

---

.drone.yml
.gitignore
Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/apiActivity/list.feature
tests/acceptance/features/bootstrap/ActivityContext.php

first set of API acceptance tests
fixes https://github.com/owncloud/activity/issues/627

api acceptance tests

---

lib/AppInfo/Application.php

Depends on https://github.com/owncloud/core/pull/34122
If there is no currentUser try to resolve a remote user by dispatching an event.

[Not that dirty solution] Get the remote user for the federated share

---

tests/acceptance/config/behat.yml
tests/acceptance/features/webUIActivity/deleteAndRestore.feature
tests/acceptance/features/webUIActivity/list.feature

Test deleting and restoring files are registered in the activity list

---

tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/webUIActivity/tags.feature

Acceptance test for tags activity
Part of #677

Test tags activity

---

tests/acceptance/features/webUIActivity/comment.feature

This adds acceptance tests for comments.

Acceptance test for comments

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiActivity/list.feature

test delete and restore of file and folder using API is visible in activity list

test delete and restore of file and folder using API is visible in activity list

---

tests/acceptance/features/apiActivity/list.feature

Test the sharing files with the users using API should listed in activity list

sharing with user apiActivity test

---

CHANGELOG.md
Makefile
appinfo/info.xml

Closes https://github.com/owncloud/activity/issues/678

Release 2.4.2

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/lib/ActivityPage.php
tests/acceptance/features/webUIActivity/comment.feature
tests/acceptance/features/webUIActivity/createFilesFolder.feature
tests/acceptance/features/webUIActivity/deleteAndRestore.feature
tests/acceptance/features/webUIActivity/sharingInternal.feature
tests/acceptance/features/webUIActivity/tags.feature
tests/acceptance/features/webUIActivity/updateFilesFolder.feature

This adds test for activity tab

Test activity tab

---

tests/acceptance/features/lib/ActivityPage.php
tests/acceptance/features/webUIActivity/createFilesFolder.feature
tests/acceptance/features/webUIActivity/deleteAndRestore.feature
tests/acceptance/features/webUIActivity/updateFilesFolder.feature

This adds a tests for different filters in the activity.

Add tests for webui filters

---

lib/Consumer.php
lib/Controller/Activities.php
lib/Controller/Feed.php
lib/Data.php
lib/Formatter/UserFormatter.php
lib/Parameter/Collection.php
lib/Parameter/Factory.php
lib/Parameter/Parameter.php
tests/Unit/ApiTest.php
tests/Unit/MailQueueHandlerTest.php
tests/Unit/Parameter/ParameterTest.php

cleanup while I am looking at unit tests

Remove unused use

---

composer.lock

While doing PHPUnit6 refactoring, I am also bumping this (to get it done).
PHPUnit6 preparation is already done in this repo.

Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)

---

templates/personal.php

we are only printing a description, no need to be able to output raw html here.

use p() instead of echo

---

.drone.yml
tests/acceptance/features/apiActivity/list.feature
tests/acceptance/features/webUIActivityDeleteRestore/restore.feature

Add drone matrices to run test against latest stable release tarball.
Related Issue https://github.com/owncloud/QA/issues/611

Run tests against latest stable tarball release

---

tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
tests/acceptance/features/webUIActivityDeleteRestore/restore.feature

Some minor fixes on PR https://github.com/owncloud/activity/pull/748
On top of https://github.com/owncloud/activity/pull/748

some minor fixes in acceptance test for deleting/restoring files by sharer and sharee

---

CHANGELOG.md
appinfo/info.xml

Release 2.5.0

---

tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature

to match core PR https://github.com/owncloud/core/pull/36041

Adjust public link step text

---

.drone.yml

remove unnecessary drone code before we switch to starlark

federated server is not needed for webUIActivitySharingInternal

---

.drone.starlark
.drone.yml
tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
tests/acceptance/features/webUIActivityTags/tags.feature

See https://github.com/owncloud/password_policy/pull/248 for a description.
This is the same code, with config for this repo.

Implement starlark for drone

---

tests/acceptance/features/apiActivity/list.feature
tests/acceptance/features/webUIActivityDeleteRestore/restore.feature

Various tests here need the trashbin API enabled.

Adjust acceptance tests for core tech_preview setting

---

tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/webUIActivityDeleteRestore/restoreUsingWebUI.feature

webui acceptance test to restore file/folder using the webui and checking the activity
Fixed: #778 
CI

test old trashbin api by restoring deleted files using the webUi and the checking the activity

---

.drone.star

This is code that was added first for the testing app GitHub release process.

Add github_release support to drone starlark

---

.drone.star

Allow for running all acceptance tests in a matrix of `numberOfParts`
This is used by `files_primary_s3` and `encryption` to run core tests.
And other changes from recent days to support LDAP...

Update drone starlark with latest code 20191011

---

CHANGELOG.md
appinfo/info.xml

Closes #746 
- Url Formatter [#744](https://github.com/owncloud/activity/pull/744)

Release v2.5.1

---

.drone.star

This was needed for `files_external_s3`
- allow specifying extra environment variables to the scality or ceph services
- allow controlling whether to create "default"  buckets or not in scality and ceph
This PR updates the starlark code here so that this repo has the latest current starlark code for use in apps.

Extra scality and ceph flexibility in drone starlark

---

.drone.star

Add starlark code to support drone cron nightly jobs.
These are changes that were first made in the encryption app PR https://github.com/owncloud/encryption/pull/156

drone starlark code for cron nightly

---

.drone.star

These enhancements were needed for `objectstore` - that app does its own thing, rather than relying on `files_primary_s3`. So we need to be able to override the default setups that happen when `cephS3` or `scalityS3` is set to true.
So you can do stuff like:
- specify `setupCommands` for ceph or scality to override what is done by default.
- specify `filesPrimaryS3Needed` false to stop the default install/enable of `files_primary_s3`
```
'cephS3': {
'setupCommands': [
'wait-for-it -t 60 ceph:80',
'cd /var/www/owncloud/server',
'cp apps/objectstore/tests/env/s3-ceph.config.php config/autotest-objectstore-s3-ceph.config.php'
],
'filesPrimaryS3Needed': False,
'createFirstBucket': False
},
```

Add flexibility in drone starlark to override default ceph and scality setups

---

tests/Unit/BackgroundJob/EmailNotificationTest.php
tests/Unit/Controller/OCSEndPointTest.php
tests/Unit/DataTest.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580

Implement coding-standard 2.0.0

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/activity/issues/816

Merge back Release 2.5.2

---

.drone.star

Use mysql as database for federated server while running acceptance tests in drone CI.

Drone: Update drone.star to use mysql on federated server as database

---

tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature

Fixes https://github.com/owncloud/activity/issues/829
Change Core steps that were recently changed regarding creating new public links.

[Tests-only]: Fix acceptance test steps changed in core

---

.drone.star

Issue https://github.com/owncloud/QA/issues/640

Update starlark code for Oracle and X-Forwarded-For

---

.drone.star

Like done in core PR https://github.com/owncloud/core/pull/37031

Correct the Oracle Db auth in .drone.star

---

.drone.star

which was added for files_prinary_s3 in PR https://github.com/owncloud/files_primary_s3/pull/317

[Tests-Only] Add extraTeardown functionality to .drone.star

---

tests/Unit/ConsumerTest.php

[Tests-Only] Adjust tests to run with php 7.4

---

tests/acceptance/features/bootstrap/WebUIActivityContext.php
vendor-bin/behat/composer.json

Part of https://github.com/owncloud/QA/issues/647

Implement phpunit v8

---

tests/Unit/Command/SendEmailsTest.php
tests/Unit/Controller/FeedTest.php
tests/Unit/Controller/SettingsTest.php
tests/Unit/NavigationTest.php

Related issue https://github.com/owncloud/QA/issues/647

Adjust unit tests for phpunit8

---

package.json
yarn.lock

Update dependencies to get rid of the security notifications

update karma and karma-jasmin

---

tests/acceptance/features/bootstrap/ActivityContext.php

Fix failing acceptance tests due to change in `core`
Fixes https://github.com/owncloud/activity/issues/871

[Tests-only] Fix failing tests after core changes

---

CHANGELOG.md
appinfo/info.xml

Release 2.5.4

---

tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature

core PR https://github.com/owncloud/core/pull/37881 change the words of the accept-decline-share test steps a little bit. Adjust the word here so it passes.

[Tests-Only] Update wording of accept and decline share test steps

---

.drone.star

- remove some double-spaces
- camel case some more variable and function names (so my IDE stops shouting at me about typos)
We are about to make other functional changes for SonarCloud, so doing this little cleanup first.

[tests-only] Minor cleanup in .drone.star

---

.drone.star
.gitignore
sonar-project.properties

Change codecov to SonarCloud for coverage reporting. 
https://github.com/owncloud/QA/issues/649
- CI

[tests-only] send code coverage to sonarCloud

---

.drone.star

See demonstration PR https://github.com/owncloud/search_elastic/pull/188
1) Give `.drone.star` knowledge about how to run Elastic Search as a service, and how to setup the app. This is similar to how `.drone.star` currently knows how to `setupCeph` `setupScality` and run a `cephService` or `scalityService`
2) Allow a list of Elastic Search versions to be specified in the config section.
This will help in testing support for multiple Elastic Search versions. And will help if we want to test other apps with Elastic Search installed at the same time.
Note: merging needs to be done carefully along with other PRs here that are changing `.drone.star` - make sure that whatever is merged has been rebased to master with fresh CI...

[tests-only] Add elastic search setup code to .drone.star

---

.drone.star

Improve starlark code for acceptance tests.

[Tests-Only] improve starlark code for acceptance tests

---

.drone.star

add purge cache step after sonarcloud analysis

[Tests-Only][ci] purge the coverage cache after sonar analysis

---

.drone.star
sonar-project.properties

Update starlark to use empty strings instead of None
This was causing error in `drone starlark generate` which we do in the user_ldap app

[Tests-Only][CI] Set env vars to empty strings instead of None

---

.drone.star

Apply `.drone.star` changes first done in https://github.com/owncloud/ransomware_protection/pull/251

[tests-only] Add option to run a pipeline in CI for both a PR and cron

---

tests/acceptance/features/apiActivity/list.feature
tests/acceptance/features/webUIActivityComments/comments.feature
tests/acceptance/features/webUIActivityCreateUpdate/updateFilesFolder.feature
tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
tests/acceptance/features/webUIActivityDeleteRestore/restoreUsingWebUI.feature
tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
tests/acceptance/features/webUIActivityTags/tags.feature

like was done in core last week.
Fixes CI

[tests-only] Specify small or large skeleton in tests

---

lib/FilesHooks.php

Goes together with https://github.com/owncloud/core/pull/38631 (although the changes do not heavily depend on each other, so no braking change).
Fixes https://github.com/owncloud/enterprise/issues/4455

Add shareExpire-param to indicate if a share was removed due to its expiry

---

.drone.star

This PR adds a feature that enables us to run specific test suites in CI
part of https://github.com/owncloud/QA/issues/670

[tests-only] Feature to debug specific test suites in CI

---

.drone.star

related https://github.com/owncloud/QA/issues/673
Dont show apache logs for owncloud server in CI

[CI] Dont show apache logs for owncloud server in CI

---

.gitignore
Makefile
lib/Api.php
lib/BackgroundJob/EmailNotification.php
lib/Command/SendEmails.php
lib/Controller/Activities.php
lib/Controller/EndPoint.php
lib/Controller/Feed.php
lib/Controller/OCSEndPoint.php
lib/Controller/Settings.php
lib/Data.php
lib/DataHelper.php
lib/Extension/Files.php
lib/Extension/Files_Sharing.php
lib/FilesHooks.php
lib/MailQueueHandler.php
lib/Navigation.php
lib/Parameter/Factory.php
lib/Parameter/Parameter.php
lib/UserSettings.php
templates/html.notification.php
tests/Unit/Command/SendEmailsTest.php
tests/Unit/Mock/Extension.php
tests/acceptance/features/bootstrap/ActivityContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/ActivityPage.php
tests/acceptance/features/lib/ActivitySettingForm.php
vendor-bin/owncloud-codestyle/composer.json

Part of https://github.com/owncloud/coding-standard/issues/22
The similar style change in core is PR https://github.com/owncloud/core/pull/38828
This can be done to each app "some time" (no hurry). It does not break or change any behavior, so it can happen and the new code can be released whenever there happens to be an app release - it is not dependent on anything.

Update coding-standard to major version 3

---

lib/FilesHooks.php

fixes https://github.com/owncloud/activity/issues/965

Fix check for expired public links

---

.drone.star

Issue https://github.com/owncloud/QA/issues/672
Putting `full-ci` in the PR title overrides the default early-fail.
cron "nightly" overrides the default early-fail. We want to see the results of all pipelines in the nightly cron jobs.

[tests-only] Add earlyFail capability to CI

---

tests/acceptance/features/apiActivity/list.feature

Issue #968 
Test added for activity list on share expiration.
- user share
- group share
- public link

[test only] add test for activity list on share expiration.

---

tests/acceptance/features/bootstrap/ActivityContext.php

core PR https://github.com/owncloud/core/pull/39036 changed the parameters of various test helper functions. Adjust the calls.

[tests-only] [full-ci] Adjust calls to test helper functions

---

.drone.star

That were done in https://github.com/owncloud/search_elastic/pull/218
This makes consistent use of double-quotes for strings.

[tests-only] Apply latest .drone.star quotes changes

---

.drone.star

Related https://github.com/owncloud/activity/issues/997
Related https://github.com/owncloud/updater/pull/616
Update drone.star file to include phplint and skip enable app option

[CI] Update drone.star file to include phplint and skip enable app option

---

.drone.star

add install js dependency option in .drone.star file
Related https://github.com/owncloud/activity/issues/995
Related https://github.com/owncloud/files_classifier/pull/524

[CI] add install js dependency option in .drone.star file

---

.drone.star
Makefile

Related issue https://github.com/owncloud-ci/php/issues/137

[tests-only] Use nodejs 14

---

sonar-project.properties
tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature

core PR https://github.com/owncloud/core/pull/38877 changed UI mentions of "remote" to "federated".
Make the needed changes to tests here.

[tests-only] Adjust federated share activity tests

---

.drone.star

This is drone starlark code from https://github.com/owncloud/contacts/pull/724

[tests-only] Provide separate appInstallCommandPhp and appInstallCommandJavaScript CI options

---

tests/acceptance/features/bootstrap/ActivityContext.php
tests/acceptance/features/bootstrap/WebUIActivityContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/ActivityPage.php
tests/acceptance/features/lib/ActivitySettingForm.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Release 2.7.0

---

package.json
yarn.lock

This PR is to make drone start for #1058

Bump karma from 6.3.13 to 6.3.15

---

package.json
yarn.lock

Bump karma from 6.3.15 to 6.3.16

---

.drone.star

part of : 
https://github.com/owncloud/QA/issues/730

[CI] Implement skip-if-unchanged in drone

---

package.json
yarn.lock

Bump karma from 6.3.16 to 6.3.17

---

.drone.star

This PR refactors some image references to constants and using caches images which were missed in PR  https://github.com/owncloud/activity/pull/1073  
- moving docker image references to constants
- using caches images
- Part of issue: 
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728

[CI]updated drone.star file to match the latest changes

---

package.json
yarn.lock

to make drone start for PR #1096

Bump karma-jasmine from 4.0.1 to 4.0.2

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/webUIActivityFileMoveAndRename/moveRename.feature
tests/acceptance/features/webUIActivityMoving/move.feature

[tests-only] acceptance test for move and rename activity

---

.drone.star

Sometimes we want to run PHP unit tests in CI against different core versions, to verify that an app is working OK with multiple core versions.
We already do this with acceptance tests.
This PR adds the flexibility to PHP unit tests. I am adding this flexibility to `.drone.star` in the activity app because the activity app has the "latest greatest" `.drone.star` oC10 app CI code. It can then be copied from here to apps that need to use it, and one day it will get copied to all oC10 apps (but there is no rush for that)
We want this for the upcoming Guzzle 5 to 7 major version upgrade. Various apps have code changes that we would like to make upwardly-compatible if possible. For example https://github.com/owncloud/objectstore/pull/158 and files_primary_s3.
PR #1123 demonstrates how this can …

[tests-only] [full-ci] Allow PHP unit tests to run against different core versions

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back release branch after release.
Closes #1128 
Closes #1127

Release 2.7.1

---

tests/acceptance/features/apiActivity/list.feature
tests/acceptance/features/webUIActivityComments/comments.feature
tests/acceptance/features/webUIActivityCreateUpdate/createFilesFolder.feature
tests/acceptance/features/webUIActivityCreateUpdate/updateFilesFolder.feature
tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
tests/acceptance/features/webUIActivityDeleteRestore/restoreUsingWebUI.feature
tests/acceptance/features/webUIActivityFileMoveAndRename/moveRename.feature
tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
tests/acceptance/features/webUIActivityTags/tags.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769

[full-ci] [tests-only] Refactored inter scenarios space

---

composer.lock
vendor-bin/phpstan/composer.json

- use the latest phpstan, which is 1.9.* series
- https://github.com/owncloud/QA/issues/777

Bump phpstan version to 1.9

---

vendor-bin/behat/composer.json

I missed these changes last week.

[tests-only] [full-ci] Bump behat acceptance test dependencies

---

package.json
yarn.lock

followup: https://github.com/owncloud/activity/pull/1187

chore: fix version

---

package.json
tests/js/karma.config.js
yarn.lock

Drop PhantomJs and use Firefox for javascript tests
Fixes https://github.com/owncloud/activity/issues/1189

[tests-only] Run JavaScript tests with firefox

---

package.json
yarn.lock

Bump karma-firefox-launcher from 2.1.2 to 2.1.3

---

vendor-bin/owncloud-codestyle/composer.json

similar to https://github.com/owncloud/core/pull/41258

chore: use owncloud/coding-standard 5.1

---

lib/BackgroundJob/EmailNotification.php
lib/BackgroundJob/ExpireActivities.php

This PR fixes nightly failures caused by Implicit nullable parameters issue
Related issue: https://github.com/owncloud/QA/issues/859

test(refactor): fix nullable parameters error in nightly failure
