owncloud/activity

- controller/settings.php
Currently the success message is not displayed:
Fixed:
@LukasReschke
> Fix the success msgs in the personal settings page

- js/script.js
Fixes #221 
@karlitschek can we backport this to stable7 ?
It is a "just in case" thing, but it's pretty easy and helps prevent infinite loading.
To test, add spaces/tabs before the `<?php` in `template/activities.part.php`
> Trim the response, before trying to add it to the output

- lib/backgroundjob/emailnotification.php
We create a TimeZone object from the value directly:
https://github.com/owncloud/activity/blob/83865de1b1285f4c4540f4047fba86cfbee4ee6d/lib/mailqueuehandler.php#L196
See log in https://github.com/owncloud/core/issues/14176
@LukasReschke
> Use a valid timezone name when no timezone is set

- lib/mailqueuehandler.php
Backport of #251 (master), #252 (stable8)
@karlitschek @DeepDiver1975 please approve backport to 7
@scolebrook
> [Stable7] Use displayname as user name for email recipient

- appinfo/application.php
- appinfo/routes.php
- lib/display.php
- lib/mailqueuehandler.php
- tests/apitest.php
- tests/mailqueuehandlertest.php
Fix #282
I don't feel very comfortable replacing the following calls, because they are testing specific and don't have a public replacement @DeepDiver1975 
1. `\OC_User::setUserId($user);`
```
Analysing /home/nickv/ownCloud/master/repos/activity/tests/apitest.php
1 errors
line  153: OC_User - static method call on private class
```
2. `OC_Hook::clear();`
```
Analysing /home/nickv/ownCloud/master/repos/activity/tests/bootstrap.php
1 errors
line   16: OC_Hook - static method call on private class
```
> Fix OCC app:check-code complains

- lib/data.php
- lib/display.php
Fix #289 
Backporting the fixes from #271 
@karlitschek please approve
@MorrisJobke mind reviewing/testing ;)
**Testplan:**
1. Check the box in personal settings so you get self actions
2. Create some activities
3. Uncheck the box
4. Verify no selfactions are displayed on the stream and RSS feed anymore
The second commit (display.php) does not affect existing activities of the activity app, but it might affect some other apps' activities
> Backport 271 stream notself

- lib/display.php
> Correctly generate links around the preview with scrollto= parameter

- js/script.js
- lib/parameterhelper.php
- templates/stream.item.php
- templates/stream.list.php
- tests/datahelpertest.php
- tests/parameterhelpertest.php
Broken by https://github.com/owncloud/core/pull/17075
1. Trigger an activity
2. Open activity stream
1. Headline "Today"
2. The activity
1. No headline
2. The activity
With this PR the headline is displayed again.
@MorrisJobke
> Replace tipsy with tooltip and use a different classname

- appinfo/application.php
- lib/data.php
- lib/hooks.php
- tests/apitest.php
- tests/datadeleteactivitestest.php
- tests/datatest.php
- tests/hooksdeleteusertest.php
- tests/usersettingstest.php
Replaces the `\OCP\DB` and `\OCP\User` usages with the new non-static version
And finally tests for `read()`
> Remove deprecated global usage

- js/activitycollection.js
- js/activitymodel.js
- js/activitytabview.js
- js/filesplugin.js
- lib/fileshooksstatic.php
- tests/js/activitycollectionSpec.js
- tests/js/activitytabviewSpec.js
- tests/js/karma.config.js
- tests/js/scriptSpec.js
@nickvergessen FYI
Not sure what attributes the endpoint is going to return eventually.
Everything is a dummy at the moment.
> Activity tab in files sidebar

- appinfo/application.php
- controller/activities.php
- lib/grouphelper.php
- tests/controller/activitiestest.php
- tests/grouphelpertest.php
Files in trashbin still don't work: https://github.com/owncloud/core/issues/18509
Use the ID in the parameters as well?
Fix #369 
Fix #340 
Fix #381
@PVince81
> Use the object ID to generate the preview

- appinfo/database.xml
- appinfo/info.xml
@karlitschek we could backport this easily.
The issue was reported for 8.1.3
Should we backport it? And if yes, only to 8.2 or also 8.1?
Fix #423 
@scolebrook
> Add an index to cover the expire SQL query

- css/style.css
Make it normal size and left-align it with the avatar, so that it’s like in the sidebar in Files.
Please review @nickvergessen @owncloud/designers 
I’d also like to backport this to stable9 since this looks like a bad design glitch. @karlitschek
> fix message style in activity view

- lib/mailqueuehandler.php
The session is closed at this point since it may come over CLI => :bomb:
Fixes https://github.com/owncloud/core/issues/23205
cc @nickvergessen 
cc @karlitschek Backport to 9.0.1?
> Do not register CSRF token

- controller/settings.php
- lib/usersettings.php
- tests/usersettingstest.php
> [9.0] Store the preferences as integers for postgres

- js/settings.js
Discovered while working on https://github.com/owncloud/core/pull/24081
> use $().prop('checked', ...) instead of $().attr('checked', ...)

- js/activitytabview.js
Fix #529: Use (first character of) display name for avatar in activity tab if username is unavailable same as main in view.
> fix 529: Avatar image in activity tab broken for "remote user"

- js/activitytabview.js
Reverts non-critical fix that was merged by mistake during the code freeze.
@DeepDiver1975 please approve.
I'll resend a PR so we can get the fix into 9.1.4
> Revert "fix 529: Avatar image in activity tab broken for "remote user""

- templates/personal.php
We are using this app for our owncloud instance and found out that the method name in the table header is not translated. This patch fixes this bug for the current master.
We've tested this in our test instance.
Issue: https://github.com/owncloud/activity/issues/567
> Translate the methodname in the table header

- lib/BackgroundJob/EmailNotification.php
We have an issue where an exception is triggered when too many mails are sent in one mail connection. This is uncaught which causes the background job to fail. This means the items that are sent at the beginning of this loop dont get removed from the queue and are sent multiple times.
This PR logs the exception and maintains a list of successful email attempts to cleanup after the emails have been attempted.
> Catch mail exceptions and still remove sent emails from queue

- templates/personal.php
We are using this app for our owncloud instance and found out that the method name in the table header is not translated. This patch fixes this bug.
Issue: https://github.com/owncloud/activity/issues/567
> [stable9.1] Translate the methodname in the table header

- appinfo/Migrations/Version20170724182159.php
- appinfo/info.xml
Ref https://github.com/owncloud/core/issues/26901
> Migrate to bigint

- .gitignore
- Makefile
- appinfo/info.xml
- clean gitignore
- better Makefile
- bump version to 2.3.6
- add summary to info.xml
Goal: unified Makefile.
This Makefile used for "all" apps, ongoing work on having one Makefile for all.
Still small differences.
Unified the structure of Makefile and the build output: 
- `/build/dist/appname` folder with app
- `/build/dist/appname.tar.gz` tarball
Open topics (not "activity app" specific):
- occ command, run with php -f or not? I think we should not prepend a `php -f `. Objections?
- vendor cleanup: needs more logic to skip cleanup, if no vendor folder available
- deprecate Bower in all apps, at least install bower via npm if needed
> Release Changes for master

- js/activitytabview.js
We are running ownCloud 10.0.3 with `'enable_avatars' => false` in the config.php and this issue does not occur if I change that setting to true.
When trying to list the activity of a file or folder in the sidebar, we get the following exception.
```Uncaught TypeError: element.avatar is not a function``` which stops the activity list from loading and only shows a blank list.
This pull request just adds in a check to make sure the avatar method exists before trying to run it.
> Check to see if avatar method is available in _postRenderItem()

- lib/Data.php
- tests/DataDeleteActivitiesTest.php
Fixes for clustered environments, which have a limit on rows and size of data affected by each transaction due to replication concerns.
> Chunk deleting of rows from the activity table

- js/script.js
- js/settings.js
Replace .click() with .on('click')
Fixes https://github.com/owncloud/activity/issues/637
To test:
> Prepare for jquery 2 update

- templates/email.notification.php
- templates/html.notification.php
Fixes owncloud/enterprise#2788
Mails from the activity app should contain the new mail footer with "imprint" and "privacy policy" links.
Html Footer
```php
<?php print_unescaped($this->inc('html.mail.footer', ['app' => 'core'])); ?>
```
Plain Text Footer
```
<?php print_unescaped($this->inc('plain.mail.footer', ['app' => 'core'])); ?>
```
The footer is missing.
Activity app didn't follow up with this change.
> Add new mail footers to template files.

- appinfo/Migrations/Version20181019151118.php
- appinfo/Migrations/Version20181022150134.php
- appinfo/info.xml
- set type to "longtext" for "subjectparams" and "messageparams" by increasing length
- add index "activity_time" on column "timestamp"
- add index "activity_object" on columns "object_type" and "object_id"
Fixes https://github.com/owncloud/activity/issues/652
- ~~BUG: cannot change from text to longtext because Doctrine ignores length changes, possibly related unmerged upstream PR: https://github.com/doctrine/dbal/pull/3182, also see https://github.com/doctrine/dbal/issues/2566~~ => now resorting to direct SQL
> Add missing migrations for longtext and indices

- tests/acceptance/features/webUIActivity/createFilesFolder.feature
- tests/acceptance/features/webUIActivity/list.feature
- tests/acceptance/features/webUIActivity/updateFilesFolder.feature
This adds a test for checking that the app registers the updates of files/folders correctly.
Currently, renaming files/folders (#375) and moving files/folders are not tracked.
Part of #677
> Test that activity log shows message on file/folder updates.

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/lib/ActivityPage.php
- tests/acceptance/features/webUIActivity/comment.feature
- tests/acceptance/features/webUIActivity/tags.feature
This adds a simple test for tagging and commenting for activities.
Part of #677
> Add test for simple tagging and commenting for activities

- .drone.yml
- tests/acceptance/config/behat.yml
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
The PR adds webUI acceptance tests for sharing activities related to external sharing.
#677 
:robot: 
P.S: Some of the steps used here are yet to be merged in [PR: owncloud/core/pull/34294]
> Add webUI tests for files sharing external

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivity/comment.feature
- tests/acceptance/features/webUIActivity/createFilesFolder.feature
- tests/acceptance/features/webUIActivity/deleteAndRestore.feature
- tests/acceptance/features/webUIActivity/sharingInternal.feature
- tests/acceptance/features/webUIActivity/tags.feature
- tests/acceptance/features/webUIActivity/updateFilesFolder.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
Remove login step from `user browses to activity page` step. 
This makes testing easier as we can move from one page to another without logging user out and then again logging in the user.
> remove login step from user browses to the activity page step

- tests/acceptance/features/lib/ActivityPage.php
Current xpath `activityContainerXpath` only works when there is at least one activity in the activity page
but when there is no activity it doesn't work.
So, a new check is introduced to make `waitTillPageIsLoaded()` work for both the cases.
> fix waitTillPageIsLoaded() for activity page with no activity

- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivity/tags.feature
The PR adds webUI acceptance tests for admin tags activity logs.
#677 
:robot: 
P.S: Some of the steps used here are yet to be merged in [PR: owncloud/core/pull/34294]
> Add tests for admin tags activity logs

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/lib/ActivitySettingForm.php
- tests/acceptance/features/webUIActivity/createFilesFolder.feature
- tests/acceptance/features/webUIActivity/deleteAndRestore.feature
- tests/acceptance/features/webUIActivity/sharingInternal.feature
- tests/acceptance/features/webUIActivity/tags.feature
- tests/acceptance/features/webUIActivity/updateFilesFolder.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
The PR adds webUI acceptance tests activity settings.
#677 
:robot: 
~~P.S: Some of the steps used here are yet to be merged in [PR: owncloud/core/pull/34294]~~
> Add tests for activity settings

- Makefile
Related to issue https://github.com/owncloud/QA/issues/609
Cleanup leftover rubbish related to ``COMPOSER_BIN`` and a local ``composer.phar``
These days we are everywhere expecting that `composer` is already installed on a developer or CI system.
> Cleanup Makefile unneeded composer references

- Makefile
Issue #700 
Somehow this code was added in #660 - see comment https://github.com/owncloud/activity/pull/660/files#r255856913
It duplicated the existing ``make dist`` target.
> Remove duplicate make dist target

- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivity/sharingInternal.feature
The PR adds webUI acceptance tests sharing internal operations
#677 
:robot:
> Add tests for internal sharing operations

- tests/acceptance/features/webUIActivity/sharingInternal.feature
Sharing a files with two users acceptance test added 
Demonstrating bug for #695
> Sharing a files with two users

- tests/Unit/ConsumerTest.php
- tests/Unit/Controller/ActivitiesTest.php
- tests/Unit/Controller/FeedTest.php
- tests/Unit/Controller/OCSEndPointTest.php
- tests/Unit/Controller/SettingsTest.php
- tests/Unit/DataHelperTest.php
- tests/Unit/DataTest.php
- tests/Unit/FilesHooksTest.php
- tests/Unit/Formatter/BaseFormatterTest.php
- tests/Unit/Formatter/CloudIDFormatterTest.php
- tests/Unit/Formatter/FileFormatterTest.php
- tests/Unit/Formatter/GroupFormatterTest.php
- tests/Unit/Formatter/UserFormatterTest.php
- tests/Unit/GroupHelperTest.php
- tests/Unit/MailQueueHandlerTest.php
- tests/Unit/Parameter/CollectionTest.php
- tests/Unit/Parameter/FactoryTest.php
- tests/Unit/Parameter/ParameterTest.php
- tests/Unit/UserSettingsTest.php
- tests/Unit/ViewInfoCacheTest.php
- tests/acceptance/features/bootstrap/ActivityContext.php
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/lib/ActivityPage.php
https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
1) Adjust `PHPUnit_Framework_*` to be `PHPUnit\Framework\*` (this works now in PHPUnit5 also)
"PHPUnit's units of code are now namespaced. For instance, PHPUnit_Framework_TestCase is now PHPUnit\Framework\TestCase"
2) Add `assertNull()` wrapper to tests that call a method that is expected to return nothing.
PHPUnit6 does more reporting of "risky" tests. A test that has no assertion is considered "risky". Sometimes there are valid tests like that - a test that calls some method, the method has no return and the only external behavior is that the method will throw an exception if it "does not work". In that case, the method "returning" `null` is the indication that it "worked.
This will avoid these …
> PHPunit 5 to 6 preparation

- templates/personal.php
#711 introduced regression on html rendering. This PR  reverts #711. 
Fixes #724
> Revert "use p() instead of echo"

- css/style.css
- tests/acceptance/features/apiActivity/list.feature
Similar by https://github.com/owncloud/core/pull/35147 / https://github.com/owncloud/core/pull/35199 / https://github.com/owncloud/contacts/pull/663
Fixes #727 
See https://github.com/owncloud/core/issues/35070 / https://github.com/owncloud/core/issues/33642 / https://github.com/owncloud/core/issues/33579 also
> Rename share icon to be adblock friendly

- tests/acceptance/features/bootstrap/ActivityContext.php
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivityCreateUpdate/createFilesFolder.feature
- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
- Move user creation without skeleton method from activity app to the core.
- Change 'in the webUI' to 'on the webUI' to match core change PR https://github.com/owncloud/core/pull/35375
https://github.com/owncloud/QA/issues/621
- Make CI faster in scenarios where there is no need for user files.
🤖
:notebook: This will only pass after https://github.com/owncloud/core/pull/35355 is merged.
> Move user creation without skeleton to core

- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/webUIActivityComments/comments.feature
- tests/acceptance/features/webUIActivityCreateUpdate/updateFilesFolder.feature
- tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
- tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
- tests/acceptance/features/webUIActivityTags/tags.feature
that changed in core https://github.com/owncloud/core/pull/35438
> Adjust create user steps

- CHANGELOG.md
- lib/Formatter/GroupFormatter.php
- tests/Unit/Formatter/GroupFormatterTest.php
1. Create group A
2. Have activities with group A (share a file afaik)
3. Delete group B
4. load activities
5. BEFORE: http status 500 and exception in log
6. AFTER: no error - activity is displayed
> Handle no longer existing groups

- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
Add  API and WebUI tests for checking the activities of user and groups that don't exist anymore.
Related issue #740
> Add acceptance tests for checking activity relating to users and groups that don't exist

- lib/Formatter/UrlFormatter.php
- lib/Parameter/Factory.php
- tests/Unit/Formatter/UrlFormatterTest.php
The idea of this issue https://github.com/owncloud/customer_portal/issues/411 was, to be able to notify Case owners in customer portal, when users uploaded files to case data folder. The notification needs context, so we wanted to add links to the Case details page and the Account details page. This is not possible with the `BaseFormatter`, as we can't inject a link into the href attribute of a prebuilt a-tag (url gets surrounded with a `strong`-tag). Injecting the complete a-tag is not possible as well, because the BaseFormatter sanitizes HTML.
This PR adds a URL Formatter, which expects an associative array, json encoded, to fulfill the parameter type `string` of `$parameters`, and converts it into an `a`-tag. Keys of the array can be `url`, `name` and `target`. `url` is required, …
> URL Formatter

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
- tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
Add acceptance tests for:
- deleting a shared file/folder and check activity on both sides.
- deleting a shared file/folder, restore on each side, and check activity on both sides
https://github.com/owncloud/activity/issues/747
> Acceptance test for deleting/restoring files by sharer and sharee and checking activity

- tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
Issue #752 
- adjust test step text to match what changed in core (1st commit)
- adjust "delete-restore" and "unshare" test scenarios to do more correct stuff and pass. The problem with `restore.feature:269` started to be actually reported as a fail because of extra checks added to core `TrashbinContext` `restoreElement` (2nd and 3rd commit)
- skip the moved scenario on OcV10.2 (we can investigate later, let's get the passing things merged)
> Adjust test steps because of core 35926

- .drone.yml
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
Previously we have been:
1) using the QA tarball acceptance test code when testing the app with the `daily-master-qa` tarball.
2) using the latest core master acceptance test code cloned from git when testing the app with the `10.2.1` or other release tarballs.
This sometimes creates inconsistency when core test steps have been modified, added, deleted in git core master but the `daily-master-qa` tarball is out-of-date. In that case it can be difficult or impossible to make the app CI pass - because some gherkin step text needs to be one way for `daily-master-qa` and another way for git core master.
Actually we may as well just always use the "testrunner" logic no matter which core tarball is the system-under-test.
> Always use testrunner for acceptance tests

- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
Issue https://github.com/owncloud/enterprise/issues/3497
core PR https://github.com/owncloud/core/pull/36120 corrected the behavior when a sharee tries to delete a share that they have received. From core 10.3 that API call gets a `404` and is not allowed.
So now the action of a sharee deleting their received share no longer works at all. The `given` step in these scenarios cannot happen. So the scenarios are not relevant - delete them.
> Remove 'delete a share as sharee' tests

- .drone.starlark
- .drone.yml
Instead of specifying `10.2.1` we can specify `latest` core. The download servers point `latest` to the latest core release - currently `10.2.1` then it will "automagically" switch to `10.3.0` one day...
So we will not have to touch all the app repos when there is a new core release to run against.
Note: this is the "default" test matrix for our nightly CI - we test against daily core master tarball and against the latest core release tarball.
As a separate thing we can discuss how we can also automate testing against a test release tarball (e.g. currently 10.3.0RC1). In that case:
1) we currently do not have a constant "logical" link pointing to "current core test tarball"
2) there may not always be a "current core test tarball", so sometimes we may not need to run tests against that
3) …
> Run acceptance tests against latest core release

- .drone.starlark
1) Some functions that return a "step" dictionary are returning `None` when the step is not needed. That is causing a problem when we move over to not generating `.drone.yml` locally but executing the starlark code directly in the drone server. The matrix entry ends up in the list, but gets "stuck" in the `pending` state.
Change the code so that these functions return an empty array `[]`, which can be "added" with other arrays of steps.
2) Handle empty command for installing app - when there are multiple `extraApps` to install, then one of the apps might have a command needed to install it, but other apps might not. So we need to be smarter and make sure to ignore doing the command when it is the empty string.
> Update drone starlark 20190928

- .drone.star
When looping to generate pipeline entries for acceptance tests, if there were some `webUI` entries processed after `api`  or `cli` entries, and the `webUI` entry used just the default browser, then the default got overwritten with null when the `api` or `cli` test pipeline was processed. So the `webUI` did not specify a browser - which creates a problem!
The `default` settings  should be set up at the top of `acceptance()` and not modified in the loops.
(This was noticed when trying to do ransomware_protection which has a more complex variety of test scenarios with other apps and backend storage)
> Fix default browsers for acceptance tests

- .drone.star
If a nightly build has failure, then nothing is being reported in rocketchat, because the pipelines stop once there is a failure. So the notify pipeline is never executed.
Adjust so that the notify pipeline will execute on both success and failure.
> drone notify on failure

- lib/AppInfo/Application.php
- lib/FilesHooks.php
- tests/Unit/FilesHooksTest.php
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
Currently, `$currentUser` value is `null` if the user not found. However, the class expects its value as `false` in this case. Because of that `fileCreate` method condition is not working properly.
The type conversion problem resolved, by ensuring `currentUser` value will be always a string.
Fixes https://github.com/owncloud/enterprise/issues/3554
> ensure currentUser always string in FilesHooks constructor

- .drone.star
In the last week or so we are experiencing longer times for pulling docker images, like for databases and object storage. We adjusted the "standard" wait for database services to 120 seconds. And are doing similar in https://github.com/owncloud/update-testing/pull/28
`files_primary_s3`  had some examples today where the 60 second wait was not long enough. This has been adjusted in https://github.com/owncloud/files_primary_s3/pull/260/commits/ea888d8cdcbb612992272cdc380eb82ca67c9cad
Make the same change here in the activity app so that it has current starlark code. (This is the first app in alphabetical order and so is the place that I copy "latest" code from when needed)
> Increase wait-for-it -t 120 for ceph and scality services

- .drone.star
Because core has dropped PHP 7.0 support https://github.com/owncloud/core/pull/36290
> Drop PHP 7.0 from drone CI

- .drone.star
- tests/Unit/ApiTest.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/ConsumerTest.php
- tests/Unit/Controller/ActivitiesTest.php
- tests/Unit/Controller/FeedTest.php
- tests/Unit/Controller/OCSEndPointTest.php
- tests/Unit/Controller/SettingsTest.php
- tests/Unit/DataDeleteActivitiesTest.php
- tests/Unit/DataHelperTest.php
- tests/Unit/DataTest.php
- tests/Unit/FilesHooksTest.php
- tests/Unit/Formatter/CloudIDFormatterTest.php
- tests/Unit/Formatter/FileFormatterTest.php
- tests/Unit/Formatter/UserFormatterTest.php
- tests/Unit/GroupHelperTest.php
- tests/Unit/HooksDeleteUserTest.php
- tests/Unit/MailQueueHandlerTest.php
- tests/Unit/Parameter/CollectionTest.php
- tests/Unit/Parameter/FactoryTest.php
- tests/Unit/Parameter/ParameterTest.php
- tests/Unit/PersonalTest.php
- tests/Unit/Template/RssTest.php
- tests/Unit/UserSettingsTest.php
- tests/Unit/ViewInfoCacheTest.php
- vendor-bin/behat/composer.json
1) In the acceptance tests we use `guzzle` and `phpunit` `Assert`. At the moment we "somewhat by accident" get them "for free" in core. (see https://github.com/owncloud/core/issues/36514 ) Install them with `behat` in `vendor-bin/behat` so that we have them "locally" when running acceptance tests. Then we will be able to remove that from core when we like.
2) In core the unit test infrastructure has been changed to move forward to the newer declarations of the `setUp` and `tearDown` classes with return type `void`. The app unit tests inherit from some core classes, so we have to make the matching changes here in the app. This will future-proof the tests ready for phpunit v8...
3) There is no need to install `vendor-bin-deps` in core of the testrunner. That is just a time-waste.
> Minimize dev dependency install in drone

- composer.json
- composer.lock
There are only dev dependencies for the tools in `vendor-bin` so we can bump the composer php version here from 7.0.8 to 7.1 without any effect on the app itself (i.e. the next release of the app is not necessarily required to drop PHP 7.0 support)
> Bump PHP version in composer.json

- .drone.star
- vendor-bin/behat/composer.json
It is needed by core `HttpRequestHelper.php` `parseResponseAsXml`
And there is no longer any need to `make install-composer-deps` in the testrunner core folder, because those dependencies are not used by behat any more.
> Add sabre/xml to behat dependencies

- .drone.star
The drone agents are sometimes taking "a long time" (tm) to pull docker images. In particular this is a problem when it takes a long time to pull the database image (mariadb, postgresql, oracle...). The `install-core` step waits 120 seconds for the database to become available. If the pull took more than 2 minutes, then we get a timeout in `install-core` and the pipeline fails. That means the whole build fails and it has to be started all over again. That is very annoying.
This is seen mostly first thing in the morning, when the autoscaler starts new drone agents. Specially if a lot of drone agents get started at a similar time, they seem to be slow to pull each docker image the first time. After that, they have the docker images cached, so later pulls of the docker images do not have …
> Increase wait-for-db timeout from 120 to 600 seconds

- appinfo/info.xml
- lib/BackgroundJob/EmailNotification.php
- lib/Command/SendEmails.php
- lib/MailQueueHandler.php
- lib/Parameter/Factory.php
- tests/Unit/Command/SendEmailsTest.php
- tests/Unit/MailQueueHandlerTest.php
- Create an occ command to send out all pending notifications instantly
- Don't touch existing code
1,2,3 is repeated in batches of 250 until the count of notified users becomes 0.  
1. we get all uids and all max(mail_id)  per uid. (The queue could be changed when the sending in process so we have max mail_id to work with)
2. we iterate through uids sending an email containing all user notifications for actions with `mail_id <= max(mail_id)`
3. we delete all notifications in a one go as 
```
DELETE FROM *PREFIX*activity_mq WHERE
(uid='uid1' AND mail_id<=max_mail_id_uid1)
OR (uid='uid2' AND mail_id<=max_mail_id_uid2)
...
OR (uid='uidN' AND mail_id<=max_mail_id_uidN)
> occ command to send all pending notifications

- tests/acceptance/features/webUIActivityCreateUpdate/createFilesFolder.feature
Fixes #819
Fix failing tests after the change in core by owncloud/core#36651
Add headings to the tables in feature files.
> Fix failing tests due to change in core steps: add table headings

- tests/acceptance/features/webUIActivityTags/tags.feature
The `Given` steps for deleting tags were removed in core. Adjust the scenarios here in the `activity` app to use the `When` step forms, which are more appropriate for the tests.
> Adjust tags test scenarios for steps removed in core

- tests/acceptance/features/webUIActivityTags/tags.feature
Related https://github.com/owncloud/activity/issues/740
Add acceptance test for checking that the activity by a user by the administrator after deleting the user.
> Add acceptance test for checking the activity of the user by admin after deleting the user

- .drone.star
We are sometimes seeing pipelines where we get all the way to the behat acceptance tests but the Apache server service has not yet started. Usually this is "random" slowness in pulling the needed image from docker... e.g.
https://drone.owncloud.com/owncloud/files_primary_s3/1429/130/17
```
curl: (6) Could not resolve host: server
Server on http://server is down or not working correctly.
Makefile:125: recipe for target 'test-acceptance-core-api' failed
```
After doing the fix-permissions `chown`, then wait for the server service to be reachable. This seems a logical place, because once we set those permissions on code for the server, any step after that will expect the Apache server to be functional.
This can be applied to other drone starlark in apps. Once this works here, I will apply …
> wait for apache server to be up

- lib/Controller/Settings.php
- lib/UserSettings.php
- templates/personal.php
- tests/Unit/Controller/SettingsTest.php
- Add a config option to send email notifications ASAP 
IRL it happens on the next `occ system:cron` invocation
> Add a config option to send notifications ASAP

- vendor-bin/behat/composer.json
~This is an example of running app acceptance tests with guzzle6. It uses the core acceptance test code in core branch `use-guzzle6-for-acceptance-tests` to demonstrate.
When that core PR gets merged, then we will need to do the first commit (bump guzzle to 6.5 in `vendor-bin/behat/composer.json`) in every app repo, because the apps use the core `master` acceptance test code for many steps. In particular the `Given` step that creates users! The code for that step is different in Guzzle6 and will not work from an app that tries to still use Guzzle5.~
See comment below - now this is just the needed change.
> Test with guzzle6

- lib/BackgroundJob/EmailNotification.php
- tests/Unit/BackgroundJob/EmailNotificationTest.php
> Skip disabled users and do not break the cronjob on the first unsent email

- .gitignore
which is created when running phpunit v8 tests
> Ignore .phpunit.result.cache

- .drone.star
- run some unit test pipelines with PHP 7.4 (as we do for 7.3)
- add PHP 7.4 to the default lists of PHP versions.
> Adjust drone pipelines for PHP 7.4

- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/bootstrap/WebUIActivityContext.php
- tests/acceptance/features/webUIActivityComments/comments.feature
- tests/acceptance/features/webUIActivityCreateUpdate/createFilesFolder.feature
- tests/acceptance/features/webUIActivityCreateUpdate/updateFilesFolder.feature
- tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
- tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
- tests/acceptance/features/webUIActivityDeleteRestore/restoreUsingWebUI.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
- tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
- tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
- tests/acceptance/features/webUIActivityTags/tags.feature
like in core PR https://github.com/owncloud/core/pull/37397
IMO this can be done as a background task in apps with acceptance tests. It seems to be as easy as:
replace `user0` with `Alice`
replace `User Zero` with `Alice Hansen`
replace `user1` with `Brian`
replace `User One` with `Brian Murphy`
...
Then search for "unfortunate" replacements like `$Brian` or `:Brian` that use to be `$user1` or `:user1` and put them back (or name the variables something else).
https://doc.owncloud.com/server/developer_manual/testing/acceptance-tests.html#specifying-the-actor has the table of "standard" user names, display names and email addresses.
> [Tests-Only] Use realistic Usernames

- lib/HtmlTextParser.php
- lib/MailQueueHandler.php
- templates/email.notification.php
- tests/Unit/Parsers/HtmlTextParserTest.php
Fixes https://jira.owncloud.com/browse/OC-2285
`<a href="http://localhost/index.php/f/127">Screenshot_2020-02-26 Document Classification app ownCloud marketplace.png</a>`
>  files/folders in html emails are now clickable

- .drone.star
This was introduced in https://github.com/owncloud/files_ldap_home/pull/28
Add it here in `activity` so that the drone code will be noticed and copied to other apps next time stuff changes.
> Support extraApps in drone phpstan()

- .drone.star
To match the change in core PR https://github.com/owncloud/core/pull/38077
Note: this PR is to get the "standard" drone starlark up-to-date. This env var is not actually used by the activity app CI. I will also change it in `user_ldap`  where it matters...
The change will get propagated to the other ownCloud10 app repos the next time there is an important change needed.
> Change TEST_EXTERNAL_USER_BACKENDS to TEST_WITH_LDAP

- .drone.star
related https://github.com/owncloud/QA/issues/648
dont run acceptance tests on ci after merge
Also fix coverage reporting in sonarcloud analysis
> [Tests-Only][ci] dont run acceptance tests on CI after merge

- .drone.star
- sonar-project.properties
The officially-supported mySQL is V8. Run unit tests with mySQL V8 rather than V5.*
> [tests-only] Run unit tests with mysql:8.0 in CI

- .drone.star
`minio/mc` fixed their broken release. We may as well bump to the latest tag available at https://hub.docker.com/r/minio/mc/tags?page=1&ordering=last_updated
Just do this in the `activity` app. Next time we update `.drone.star` to all other apps, we will get this non-essential change.
> [tests-only] Bump minio/mc to latest docker tag

- .drone.star
- vendor-bin/behat/composer.json
- vendor-bin/php_codesniffer/composer.json
Adjust the logic so that setting `cron` parameter to `nightly` takes priority over the setting of `pullRequestAndCron` - if both are set then `cron` `nightly` will happen.
This is needed because the `pullRequestAndCron` parameter is set to `nightly` by default (which is the setting that we want most of the time).
Without this change, when setting `cron` to `nightly` you also would have to remember to set `pullRequestAndCron` to "" (the empty string). I noticed this when doing PR https://github.com/owncloud/admin_audit/pull/355 for admin_audit.
> [tests-only] Adjust pullRequestAndCron logic in .drone.star

- .drone.star
The `owncloudci/php` docker image actually contains various other non-PHP tools tah tare used in CI. For example, `nodejs` and `npm` for Javascript. The latest `owncloudci/php:8.0` has newer versions of these packages. Use it for Javascipt CI pipelines.
This helps for other version bump PRs like #910 and https://github.com/owncloud/files_classifier/pull/428 that need a newer `nodejs` and `npm`
> [tests-only] Use latest docker CI images for Javascript pipelines

- .drone.star
- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/FilesHooks.php
- tests/Unit/ConsumerTest.php
These adjustments properly handle the activity stream for actions that were triggered by an automation (like the workflow app e.g.). They require the changes from https://github.com/owncloud/core/pull/38605 and https://github.com/owncloud/workflow/pull/255 to work.
Needed for: https://github.com/owncloud/enterprise/issues/4222
> Automations in activity stream

- .drone.star
This PR adds the ability to skip certain CI pipelines (`PhpUnitTests`, `JavascriptTest` and `acceptanceTest`)
- part of  https://github.com/owncloud/QA/issues/670
> [tests-only] Add ability to skip pipelines in CI

- tests/acceptance/features/webUIActivityDeleteRestore/restoreUsingWebUI.feature
https://drone.owncloud.com/owncloud/activity/1899
The step was removed in core, because there was a similar step already existing. Use that API step to delete files.
> [tests-only] Adjust test step for deleting files

- .drone.star
Yesterday, we discovered that this actually causes a problem when used. See https://github.com/owncloud/user_ldap/pull/637/commits/95b7e4fd7616c7090284215ac95a165911bd7bc3 
Remove it from the "standard" `.drone.star` code here in the activity app so that we do not propagate the problem again.
> Remove unneeded HOSTNAME from ldapService

- .drone.star
Problem: Some JS and/or PHP test pipelines do not have coverage enabled. If there are no pipelines with coverage enabled, the sonar-analysis pipeline is still being added to CI. But it has nothing to do, and fails because it does not find any coverage results to process.
Solution: this PR refactors `.drone.star` so that it:
1) finds all JS and PHP test pipelines that do have coverage enabled
2) adds the sonar-analysis pipeline if (1) is non-empty
3) adds any JS and PHP test pipelines that do not have coverage enabled
4) continues adding the acceptance test pipelines.
> [tests-only] Allow for no unit tests with coverage in CI

- lib/AppInfo/Application.php
- lib/Data.php
- lib/Hooks.php
Before this fix, the objectId of a received federated share activity was empty. As a result, the activity was not showing in the file sidebar. We now set the objectId by updating the activity as soon as the share has been accepted by the user.
Also fixed a bug where certain activities were not showing in `Activities by others`.
- fixes https://github.com/owncloud/activity/issues/969
- fixes https://github.com/owncloud/activity/issues/970
- Depends on https://github.com/owncloud/core/pull/38880
> Set the objectId for a received federated share activity

- .drone.star
Issue https://github.com/owncloud/QA/issues/678
1st commit) Adjust sonar-analysis step so that it overrides the default "clone" step of drone, like core PR https://github.com/owncloud/core/pull/38842
2nd commit) refactor so that we do not need `config['app']` - we can use `ctx.repo.name` to get the current name of the "app".
> [tests-only] make code coverage report correctly on PRs

- CHANGELOG.md
- appinfo/info.xml
- lib/FilesHooks.php
- sonar-project.properties
- merge after Release #943 
Closes #943
> Merge back Release 2.6.1

- .drone.star
1) In oC10 apps the acceptance test pipelines run in `/var/www/owncloud`.
We noticed yesterday, when acceptance tests fail, the comment was not getting posted to GitHub. The starlark that does that was writing to `/drone/src` and that did not work for the oC10 apps.
It was fixed in `files_primary_s3` yesterday.
This PR makes the same change in `activity` app. And it can be propagated from here to the others apps.
2) web PR https://github.com/owncloud/web/pull/5289 removed the repeated hard-coded references to `/var/www/owncloud` through the starlark code. The 2nd commit here does the same. That should reduce the chance for errors in referring to the pipeline directories.
> [tests-only] Write comments.file to the correct dir

- .drone.star
This functionality was added in https://github.com/owncloud/files_primary_s3/pull/458
Add it here, so that it gets copied to all oC10 app repos. That will avoid `files_primary_s3` having different drone starlark code.
> [tests-only] Add externalScality code to drone starlark

- .drone.star
In PR https://github.com/owncloud/files_antivirus/pull/454 I noticed that the `wait-for-it` for `elasticsearch` to start was only 60 seconds. We use 600 seconds as the usual maximum wait time for all other services to start up - that allows for days when "docker pull" is very slow.
Adjust the timeout here. Then it will get propagated to the other oC10 apps when we next copy the "standard starlark code".
> [tests-only] Adjust wait-for-it elasticsearch to 600 seconds

- .drone.star
`csrf` is disabled on the server if federated server is needed 
- FIxes https://github.com/owncloud/activity/issues/988
> [CI] Disable crsf on server if federated server is needed

- .drone.star
1) replace tab-indent with space-indent in `.drone.star`
2) add `check-starlark` pipeline to check the formatting of the drone starlark code - the same as in `owncloud/web`
> [tests-only] Format starlark

- .drone.star
1) These changes happened in https://github.com/owncloud/search_elastic/pull/215
Apply them here so that we have the starlark up-to-date.
2) Make a fix to handle the `buildJsDeps` checks better.
> [tests-only] Apply changes to .drone.star from search_elastic app

- .drone.star
- composer.json
- composer.lock
Part of https://github.com/owncloud/core/issues/39134
Similar to core PR https://github.com/owncloud/core/pull/38697
This app should still run fine on ownCloud core 10.8.0. But all installations are recommended to use PHP 7.4 nowadays anyway. (And some might be on PHP 7.3, which should be OK). So the recommended configuration would be ownCloud core 10.8.0 with PHP 7.4. And the oC10 apps all work fine with that.
> Drop PHP 7.2

- .drone.star
The `installApp` function could not return both the `install-app-js-*` and `install-app-*` steps.
I noticed this in https://github.com/owncloud/files_classifier/pull/524/commits/eac2c7f32920dbcc82450aa2e211a0f7ad65a6f8
Fix it with brackets to enclose the logic for the `install-app-js-*` step.
> [tests-only] Fix installApp in .drone.star

- tests/acceptance/features/lib/ActivitySettingForm.php
Fixes #1020 
The checkbox for enable/disable of Activity logs for "A file or folder has been shared" was just off the bottom of the visible section of the Personal General Settings page. Something recently must have recently got bigger by a few pixels.
This PR adds code to first scroll the checkbox into view, and then click it. I tested running locally with Firefox and the test failed before the change, and now passes.
The Personal General Settings page has a single scrollbar that is part of the app-content div. That scrolls the whole div which has Profile Picture, Language, Mail Notifications, Activity, and other part in it. The overall length of that div (and thus its scrollbar...) can vary depending on exactly which apps are enabled with which settings. So it is good to explicitly …
> [tests-only] [full-ci] Scroll Activity settings checkbox into view before clicking

- .drone.star
This should be the fix for issue #1037 
A test change was made in core PR https://github.com/owncloud/core/pull/39514 and that code is currently in core branch `acceptance-test-changes-waiting-2021-11`
So use that code for now.
> Use core acceptance-test-changes-waiting-2021-11 branch for acceptance tests

- .drone.star
`cliDbConversion/dbConversion.feature:30` failed.
That scenario is designed to start with sqlite DB and convert to mysql. It should only run in a special core CI pipeline.
> [tests-only] [full-ci] Do not run dbConversion core tests in app CI

- .drone.star
Change a couple more places to use PHP 7.4 in CI by default.
If there are any apps where we want to still use PHP 7.3 for some pipeline, then it is easy to put that in the `config[]` section.
> [tests-only] [full-ci] Use PHP 7.4 in CI

- .drone.star
Issue https://github.com/owncloud/core/issues/39799
PR #1067 runs the pipelines in the PR, to demonstrate that CI will pass.
In this PR #1066 those pipelines do not run - they normally only run in nightly CI.
> [tests-only] Start federated server for core-cli test pipelines

- .drone.star
Issue https://github.com/owncloud/core/issues/38679
Do not run PHP unit tests with Oracle in PRs. Only do that in the nightly CI.
https://drone.owncloud.com/owncloud/activity/2513 - there are PHP unit CI pipelines for sqlite, mariadb, mysql, and postgresql. There is no pipeline for Oracle - correct.
This is the example change to `.drone.star`. After approval and merge here, the similar update needs to be dome in all other oC10 app repos. There is no big hurry for that.
> [tests-only] Do not run PHP unit tests with Oracle by default

- .drone.star
We can specify `extraApps` in the config of various test sections in `.drone.star`. Nowadays `files_external` is a built-in core app that is disabled by default. We want to enable it, but we don't need to clone it.
Make the code more flexible so that it does not `git clone` the app if the app code already exists. The code is taken from the way this is already done in `ownclud/core`
This change was first made in search_elastic PR https://github.com/owncloud/search_elastic/pull/266 and works.
This PR applies the change to the activity app. It can be copied from here to other apps.
> [tests-only] [full-ci] Adjust installExtraApps to be more flexible about app install

- .drone.star
because some core tests are testing with local_storage and that requires the files_external app to be enabled.
> [tests-only] enable files_external app when running core tests

- .drone.star
Nothing is failing in the activity app CI. But it will be easiest in future if we make sure that the federated server in CI has the files_external app enabled. files_external app was recently disabled by default in core.
This small change to the drone CI can get copied to other apps whenever we have a need to copy.
> [tests-only] Enable files_external app in federated server

- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
This PR adds the word `link` to steps to match the step implementation.
- Fixes https://github.com/owncloud/activity/issues/1110
> [tests-only] [full-ci] Refactored steps, added  missing word

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiActivity/list.feature
This PR adds a scenario to check the activity list after the share is expired for the federated share.
Part of issue https://github.com/owncloud/activity/issues/968
> [full-ci] [tests-only] Added scenarios to check activity list after share is expired for federated share

- composer.json
- vendor-bin/behat/composer.json
- vendor-bin/php_codesniffer/composer.json
Similar to core PR https://github.com/owncloud/core/pull/40395
Get these versions up-to-date in the various `composer.json` files so that we are easily aware of what versions are really running in CI etc.
> [tests-only] Update vendor-bin tool versions to current minor versions

- .drone.star
This is code from PR #1138 without actually changing the `owncloudci/php` docker image. It adds code to just use the first 3 characters of the `owncloudci/php` docker image tag when generating pipeline names and coverage report names.
Similar code was done in wopi https://github.com/owncloud/wopi/pull/220 and core https://github.com/owncloud/core/pull/40409
It will be useful to have this merged here in the activity app. Then when we next need to propagate CI code changes to other apps, this will be here.
> [tests-only] [full-ci] Adjust drone code to allow for variation of PHP docker images

- .drone.star
These were in `.drone.star` in brute_force_protection app. Do the same here in the activity app.
> [tests-only] [full-ci] Use browserService in more places in .drone.star

- tests/acceptance/features/apiActivity/list.feature
- tests/acceptance/features/bootstrap/ActivityContext.php
Added a scenario to describe the activity generation when adding a server on a public link share.
- Part of https://github.com/owncloud/activity/issues/800
- Needs core PR https://github.com/owncloud/core/pull/40437 to be merged first.
---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> [tests-only] add API tests to add owncloud server for a public link share

- tests/acceptance/features/webUIActivitySharingExternal/publicLinkSharingFederation.feature
Added a scenario to describe the activity generation when adding a server on a public link share.
- Part of https://github.com/owncloud/activity/issues/800
- Needs core PR https://github.com/owncloud/core/pull/40451 to be merged first
> [tests-only] [full-ci] add webUI tests to add owncloud server for a public link share

- .drone.star
https://github.com/owncloud/core/pull/40442 changed the email server used in tests from mailhog to inbucket. It also changed the tag used in feature files from `@mailhog` to `@email`
There are no uses of the `@mailhog` tag in this activiry repo. But this PR updates `.drone.star` to have the same email server code changes as in the other apps that are affectced. For example, see https://github.com/owncloud/guests/pull/531
This will make it easier in future when we propagate `.drone.star` changes to the other oC10 apps.
Issue https://github.com/owncloud/QA/issues/771
> [tests-only] [full-ci] Update .drone.star to use inbucket for email

- .php-cs-fixer.dist.php
- appinfo/Migrations/Version20161122092159.php
- appinfo/Migrations/Version20170724182159.php
- appinfo/Migrations/Version20181022150134.php
- lib/Consumer.php
- lib/Controller/Activities.php
- lib/Controller/EndPoint.php
- lib/Controller/OCSEndPoint.php
- lib/FilesHooksStatic.php
- lib/Formatter/GroupFormatter.php
- lib/Formatter/UrlFormatter.php
- lib/Hooks.php
- lib/HtmlTextParser.php
- lib/Parameter/IParameter.php
- lib/PersonalPanel.php
- lib/PlainTextParser.php
- lib/ViewInfoCache.php
- templates/stream.app.navigation.php
- tests/acceptance/features/lib/ActivityPage.php
- tests/unit/Formatter/BaseFormatterTest.php
- tests/unit/Formatter/GroupFormatterTest.php
- tests/unit/Formatter/UrlFormatterTest.php
- tests/unit/Formatter/UserFormatterTest.php
- tests/unit/MailQueueHandlerTest.php
- tests/unit/Parsers/HtmlTextParserTest.php
- vendor-bin/owncloud-codestyle/composer.json
`owncloud/coding-standard` 4 uses the latest php-cs-fixer release.
That can do some strange indenting in code with mixed HTML and PHP. That happens in some `templates/*.php` files. I have excluded `templates/html.notification.php` so that the indenting does not get changed.
A similar thing was done in core PR https://github.com/owncloud/core/pull/40490
Issue https://github.com/owncloud/QA/issues/779
> Implement owncloud/coding-standard 4

- .drone.star
This is the new code from WND PRs https://github.com/owncloud/windows_network_drive/pull/418 and https://github.com/owncloud/windows_network_drive/pull/419
Adding it here in the activity app CI logic so that it will be in the "standard" oC10 app CI code, and will get copied to the other repos next time we need to do a general update of the drone starlark rate.
> [tests-only] [full-ci] Add wait-for-samba drone CI code

- .drone.star
See https://github.com/owncloud/files_ldap_home/pull/67 where this code was first added.
In some cases we need to be able to install extra apps when running `phan` so that `phan` can find code in another app that is referenced.
> [tests-only] [full-ci] Allow extra apps to be installed during phan CI pipelines

- .drone.star
- tests/drone/check-daily-update.sh
- tests/drone/validate-oc-daily-tarball.sh
Added CI pipeline to check whether the daily-master-qa tarball is up to date or not. The tarball is considered up to date if its build date is `today` or `yesterday` 's date.
Test runs:
Passing: https://drone.owncloud.com/owncloud/activity/3118/1/2
Failing: https://drone.owncloud.com/owncloud/activity/3117/1/2
Fixes https://github.com/owncloud/QA/issues/760
> Add drone pipeline to check the oc10 daily tarball build

- .drone.star
1) https://github.com/owncloud/search_elastic/commit/fe9598651d032188ed9961d7aaf05925c5813f91 adjusted the elasticsearch URL in `.drone.star`. Makae the same change here to keep the code in the activity app up-to-date
2) Add logic so that validateDailyTarballBuild is only done if it is set in the drone config. That will allow us to copy the code the same when we copy to other oC10 app repos, and to control that pipeline from the drone config.
> Adjust elasticsearch url and validateDailyTarballBuild

- vendor-bin/behat/composer.json
Due to changes in core with this PR https://github.com/owncloud/core/pull/40619. Certain Apps requires to have a package `json-assertion` which was added in core. This PR adds the required package.
https://github.com/owncloud/QA/issues/800
> [tests-only][full-ci]Add `json-assert` to activity app

- composer.lock
- vendor-bin/behat/composer.json
- vendor-bin/owncloud-codestyle/composer.json
- vendor-bin/phpstan/composer.json
I just made a new release 4.1.0 of owncloud coding-standard https://github.com/owncloud/coding-standard/releases/tag/4.1.0
That uses a newer version of php-cs-fixer, which passes locally for me.
This PR updates the version numbers of dependencies in `vendor-bin` to the current minor versions that are in use. That can be helpful when there are problems with some new release of a dependency - at least we have "documented" which minor version is currently working correctly.
CI
> [tests-only] [full-ci] Update vendor-bin dependencies

- lib/Command/SendEmails.php
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630
> Always return an int from Symfony Command execute method

- phpstan.neon
Fixes #1174 
The code for the `EventDispatcherInterface::dispatch` had already been updated for the Symfony 5 parameter order. Now that Symfony 5 is really in use in oC10 core, `phpstan` no longer complains about the order of the parameters.
Remove the error from `ignoreErrors` in `phpstan.neon`
> [full-ci] [tests-only] Remove 'dispatch' message from phpstan.neon

- .drone.star
This logic was added yesterday to user_ldap CI https://github.com/owncloud/user_ldap/pull/790
Add it to activity app CI code so that the common code for oC10 app CI is up-to-date.
> [tests-only] [full-ci]Add federatedServerVersion flexibility to .drone.star

- .drone.star
- It is no longer possible to post a GitHub comment when an acceptance test pipeline fails. The token is no longer available to PRs. So remove this from CI.
- The earlyFail setting is not used any more in the code, so remove it.
Part of issue https://github.com/owncloud/QA/issues/820
> [tests-only] [full-ci] Remove githubComment and unused earlyFail from drone CI

- package.json
- yarn.lock
Bump security related vendor js dependencies, some dependencies still do not have fixed the peer dependency.
https://github.com/owncloud/activity/security/dependabot
https://github.com/owncloud/activity/security/dependabot/16, no upstream solution available, bumped via yarn resolutions
https://github.com/owncloud/activity/security/dependabot/5, no upstream solution available, bumped via yarn resolutions
https://github.com/owncloud/activity/security/dependabot/13, no upstream solution available, bumped via yarn resolutions
> chore: bump security related js vendor dependencies

- tests/acceptance/features/bootstrap/ActivityContext.php
Methods to get the created link share data was changed in PR https://github.com/owncloud/core/pull/40919. I have changed the tests with the updated methods
Fixes https://github.com/owncloud/activity/issues/1193
> [tets-only] use updated link-share methods to get data

- tests/acceptance/features/bootstrap/ActivityContext.php
In preparation of php8.2 support - see https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
Similar to core https://github.com/owncloud/core/pull/40995
This syntax was only in the test code, so there is no need to make sure a release happens etc.
> [tests-only] fix: drop usage of ${}
